services:
    umbraco:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 8080
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:8080
            - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
            - ASPNETCORE_HTTPS_PORT=443
            - Umbraco__CMS__Unattended__InstallUnattended=true
            - Umbraco__CMS__Unattended__PackageMigrationsUnattended=true
            - Umbraco__CMS__Unattended__UpgradeUnattended=true
            - Umbraco__CMS__WebRouting__UmbracoApplicationUrl=${PUBLIC_URL:-http://lsoco8cokk8k8cowks8wog8w.147.93.6.245.sslip.io}
        volumes:
            - umbraco-data:/app/umbraco/Data
            - media:/app/wwwroot/media
        restart: unless-stopped

volumes:
    umbraco-data:
    media:
