services:
    umbraco:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 8080
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
            - ASPNETCORE_URLS=http://+:8080
            - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
            - ASPNETCORE_HTTPS_PORT=443
            - Umbraco__CMS__Unattended__InstallUnattended=true
            - Umbraco__CMS__Unattended__PackageMigrationsUnattended=true
            - Umbraco__CMS__Unattended__UpgradeUnattended=true
            - Umbraco__CMS__WebRouting__UmbracoApplicationUrl=${PUBLIC_URL:-http://localhost:8080}
            - Umbraco__CMS__Security__BackOfficeHost=${PUBLIC_URL:-http://localhost:8080}
        volumes:
            - umbraco-data:/app/umbraco/Data
            - media:/app/wwwroot/media
        restart: unless-stopped

volumes:
    umbraco-data:
    media:
