services:
    umbraco:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:8080
        volumes:
            - umbraco-data:/app/umbraco/Data
            - media:/app/wwwroot/media
        restart: unless-stopped

volumes:
    umbraco-data:
    media:
